services:
  ffapi:
    build: .
    ports:
      - "3000:3000"
    environment:
      PUBLIC_BASE_URL: "http://localhost:3000"
      PUBLIC_DIR: "/data/public"
      WORK_DIR: "/data/work"
      RETENTION_DAYS: "7"
    volumes:
      - ./public:/data/public
      - ./work:/data/work
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'      # Max 4 CPU cores
          memory: 4G     # Max 4GB RAM
        reservations:
          cpus: '0.5'    # Reserve at least 0.5 cores
          memory: 512M   # Reserve at least 512MB
    # Health check configuration
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:3000/health').read()"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
